### ISSUE TITLE
Support tenants

### ISSUE THREAD

**Issue by papyr** [SavageLearning/Machete#121]
Hello, can you support tennants where different company's groups such as manager and employees.

thanks

**Comment by jcii** [comment]
Hi Paula, 

I don't understand your question; are you asking if an instance of Machete can have separate data? Currently every work center that uses Machete has a separate database. all the records are separate.

Machete isn't a service offered to the public; it's offered through ndlon.org. You are, however, welcome to use the source code under the GPL license.

**Comment by papyr** [comment]
Hi @jcii 

My question was I am using this to learn some aspects of the code. My question is how can we seperate two groups of users. For e.g. Coke has managers and employees, so does Nike.

Here when they register and apply, the Coke managers should only see their own employees in Coke, but they share the same Role name managers, so how do I keep these separate. Is it possible to check something off while registering.

**Comment by jcii** [comment]
when i designed this, the requirements didnt need multi-tenant. it was assumed that each client/tenant/company would maintain a separate application server and database. when we put it in the cloud, we made multiple IIS instances to separate each tenant. it's a bit of a design flaw at this point. the cloud costs are increased by this design decision.

**Comment by jcii** [comment]
Are you using Machete?
