### ISSUE TITLE
Bug: Severity	Code	Description	Project	File	Line	Suppression State Error	CS0117	'Mapper' does not contain a definition for 'CreateMap'	Machete.Web	

### ISSUE THREAD

**Issue by papyr** [SavageLearning/Machete#122]
Hi, can you please update to 4.6.2 the current framework , and latest nugets. Its no longer compiling

EFCodeFirst is now part/merged into EF

Identity Role is also renamed to roleManager.Role

Severity    Code    Description Project File    Line    Suppression State
Error   CS0117  'Mapper' does not contain a definition for 'CreateMap'  Machete.Web C:\Users\paula\Machete\Machete.Web\Helpers\MacheteMapper.cs 59  Active

**Comment by jcii** [comment]
Hi Paula,

May I ask how you're using MAchete? Are you associated with one of the NDLON centers?

**Comment by papyr** [comment]
no, just trying it out...

**Comment by jcii** [comment]
ok, cool. it was mostly written in 2011. im doing a last round of performance tweaks on this code base, then it will probably go maintenance-only. im going to re-write it in nodejs.

**Comment by jcii** [comment]
I've refactored most of the mappings; master branch should build and use localDB. closing this bug.
