### ISSUE TITLE
On the "People" page there's no way to display more than the first ten results

### ISSUE THREAD

**Issue by chaim1221** [SavageLearning/Machete#137]
![image](https://cloud.githubusercontent.com/assets/3819970/22631030/533027ee-ebba-11e6-86d6-6223d133dcf2.png)

*Steps to reproduce*
1. Create more than ten persons, or start with a database with more than ten persons.
2. Create an nth person.
3. Click on the "People" tab in Machete.
4. Observe that there is no way to see the person's record.

_Note_ that the "Search" function works to find the worker, if they have a unique name.

**Comment by jcii** [comment]
fixed by enabling pagination. main complaint used to be that they couldnt search member numbers from the search box, so they loaded all person records and used the browser to search.
i've fixed the search box to search member numbers,
