### ISSUE TITLE
Activities recurring option is broken.

### ISSUE THREAD

**Issue by esteban-gs** [SavageLearning/Machete#179]
When creating a recurring event, the events created take me here, instead of the usual activity sign in page.

This happens with all the events created with this "recurring events" function

![image](https://cloud.githubusercontent.com/assets/26440947/24065174/72acc16e-0b26-11e7-903c-0b2cb867227b.png)

**Comment by jcii** [comment]
existing bug in 1.10

**Comment by jcii** [comment]
fixed v1.11.1

**Comment by esteban-gs** [comment]
It works fine, but I got this prompt trying to delete future events ![image](https://cloud.githubusercontent.com/assets/26440947/24923467/80bc489a-1ea6-11e7-8350-eca7229d839b.png)

**Comment by jcii** [comment]
fixed again..
