### ISSUE TITLE
WO dates broken in worker profile

### ISSUE THREAD

**Issue by esteban-gs** [SavageLearning/Machete#202]
![image](https://cloud.githubusercontent.com/assets/26440947/25149109/1ff95fe8-2432-11e7-8295-4adb25173001.png)

**Comment by jcii** [comment]
It's in all WorkAssignment list queries

![image](https://cloud.githubusercontent.com/assets/593930/25158657/05f90576-245f-11e7-9ca4-1d4e25a7c86e.png)

**Comment by jcii** [comment]
fixed
