### ISSUE TITLE
Cancelled assignment no longer displayed in pink. 

### ISSUE THREAD

**Issue by esteban-gs** [SavageLearning/Machete#207]
Work assignments for cancelled work orders are no longer different (after update) in color from assignments in active work orders. Before update, cancelled assignments were displayed in pink or orange.
Work orders: 85031 and 85034
![image](https://cloud.githubusercontent.com/assets/26440947/25194113/3be304d6-24ee-11e7-8c93-ece2947cebcb.png)

![image](https://cloud.githubusercontent.com/assets/26440947/25194180/6b5b653c-24ee-11e7-9683-9330d48dba6d.png)

**Comment by jcii** [comment]
asmtStatus is coming across as null from AutoMapper

![image](https://cloud.githubusercontent.com/assets/593930/25195661/2d50654e-24f3-11e7-8977-cd4ced705ef5.png)

**Comment by jcii** [comment]
fixed
