### ISSUE TITLE
Hire online page does not work fully. 

### ISSUE THREAD

**Issue by esteban-gs** [SavageLearning/Machete#208]
Hire online is down

![image](https://cloud.githubusercontent.com/assets/26440947/25244913/6b414d04-25b7-11e7-9209-26f1b0bb6734.png)

**Comment by jcii** [comment]
https://github.com/SavageLearning/Machete/blob/master/Machete.Web/Controllers/HirerWorkOrderController.cs#L216

Previous consultants' hardcoded the number of skills possible...

**Comment by jcii** [comment]
fixed
