### ISSUE TITLE
Expired Workers May Not Expire

### ISSUE THREAD

**Issue by chaim1221** [SavageLearning/Machete#212]
During a support email on 5/3 I mentioned that centers can use the Expired Worker feature to keep track of membership. A test of the feature proved successful but during a review of the actual code we discovered that the code only fires under one circumstance, i.e., when someone goes to the Workers page, the task is fired from the WorkerController.

![capture](https://cloud.githubusercontent.com/assets/3819970/25691142/0f18c336-304d-11e7-99ad-4893d41de967.PNG)

https://github.com/SavageLearning/Machete/blob/master/Machete.Web/Controllers/WorkerController.cs#L63 (edited)

https://github.com/SavageLearning/Machete/blob/master/Machete.Service/WorkerService.cs#L169

This would more properly be done on app startup or as a separate AzureFunction.

**Comment by jcii** [comment]
I moved the expiration and reactivation to webpage startup...we'll see if that is sufficient
