### ISSUE TITLE
End user cannot add or edit income categories because they do not appear in the SelectList

### ISSUE THREAD

**Issue by chaim1221** [SavageLearning/Machete#219]
For a ticket for Graton on 5/7/2017 I was asked to once again update the income categories, but we determined that the way I'd done it in October was wrong. Dev asked to add new income categories and make the old ones inactive.

1. There's no inactive flag.
2. The end user cannot manage income categories because they don't appear in the SelectList.

![fieldsindb](https://cloud.githubusercontent.com/assets/3819970/25789177/6f1180fc-3363-11e7-87cb-51522f66a072.png)

These are the fields in the database. In order to make lookups inactive, there would have to be an Active field that has a boolean value.

In addition, here is the line where the SelectList is retrieved from the ViewBag:
https://github.com/SavageLearning/Machete/blob/master/Machete.Web/Views/Config/Index.cshtml#L18

Here is the line where the Controller populates the ViewBag:
https://github.com/SavageLearning/Machete/blob/master/Machete.Web/Controllers/ConfigController.cs#L51

And here is the line where what appears in the SelectList is hardcoded:
https://github.com/SavageLearning/Machete/blob/master/Machete.Web/Helpers/Defaults.cs#L104

We would need to change the hardcoded enumeration on Line 104 above to a complete enumeration of the properties of `LCategory.cs` (such as with the GetProperties() method) in order to have "income" and other categories not listed in the SelectList actually appear.

http://stackoverflow.com/a/9893050/2496266

**Comment by jcii** [comment]
Pre-implemented prior to request. Machete Pro-cog dept.
