### ISSUE TITLE
"activities attendance by activity" numbers don't make sense

### ISSUE THREAD

**Issue by esteban-gs** [SavageLearning/Machete#243]
Machete numbers (notice "gardening" activity)
![sghsdfghsgh](https://cloud.githubusercontent.com/assets/26440947/26473387/ec43b6f8-415f-11e7-9391-3e5201ebd1aa.png)

Report numbers 
![image](https://cloud.githubusercontent.com/assets/26440947/26473442/3b908844-4160-11e7-8ee2-bb3921607bfc.png)

**Comment by esteban-gs** [comment]
Date range is from 5/1/16-5/1/2017

**Comment by jcii** [comment]
updating test database with latest data

**Comment by jcii** [comment]
Updated test database with current data from caa database. numbers now make sense.
