### ISSUE TITLE
Reports: Some original reports fail to load

### ISSUE THREAD

**Issue by chaim1221** [SavageLearning/Machete#259]
For Graton in production, 
 - Worker Details, monthly summary
 - Worker Details, itemized jobs
 - Worker Details, signin summary
fail to load. This was not an issue in test.

**Comment by chaim1221** [comment]
These are still not working since running Work Orders update query. They simply return no data.

**Comment by jcii** [comment]
So I'd look at them on Casa's prod site and see if the data looks useful. I think they're useful.

**Comment by chaim1221** [comment]
Same issue on casa-prod; reports don't load.

**Comment by chaim1221** [comment]
Issue was that there was no member number upon which to collate data for the "worker details". PEBKAC
