### ISSUE TITLE
Urgent -Seattle City report  - update activities counted under "Counts of members who participated in job skill training or workshops"

### ISSUE THREAD

**Issue by esteban-gs** [SavageLearning/Machete#271]
"Counts of members who participated in job skill training or workshops" should include the following activities: 

1. Yardwork
2. Safety and labor rights
3. Renew/Ergonomic
4. Moving
5. Homecare/ergonomic
6. Green Clean
7. Gardening
8. Ergononic
9. Electric Hazards
10. Chemical Hazards
11. Caregivers Class

	SELECT ASIs.dwccardnum as cardnum, MIN(dateStart) as signindate
		FROM dbo.Activities Acts
		JOIN dbo.ActivitySignins ASIs ON Acts.ID = ASIs.ActivityID
		JOIN dbo.Lookups Ls ON Acts.name = Ls.ID
		WHERE dateStart >= @beginDate AND dateStart <= @enddate AND
		(Ls.ID = 182 OR Ls.ID = 181 OR Ls.ID = 180
		OR Ls.ID = 179 OR Ls.ID = 178 OR Ls.ID = 134
		OR Ls.ID = 168 OR Ls.ID = 156 OR Ls.ID = 152
		OR Ls.ID = 145 OR Ls.ID = 135 OR Ls.ID = 104)

**Comment by jcii** [comment]
updated. you'll see that i replaced the IDs with Keys...a little less cryptic
