### ISSUE TITLE
Add living situation yes/no to  "Member Attendance Metrics report". 

### ISSUE THREAD

**Issue by esteban-gs** [SavageLearning/Machete#278]
Please add a column to report for living situation to "Member Attendance Metrics report. yes/no for homelessness. We need this by oct. 12th for our united way report. 

![image](https://user-images.githubusercontent.com/26440947/31136261-89b3be60-a81c-11e7-98ba-a170b4f4f63c.png)

**Comment by jcii** [comment]
added
