### ISSUE TITLE
Hirer UI Facebook authentication failed

### ISSUE THREAD

**Issue by esteban-gs** [SavageLearning/Machete#286]
This issue appeared while I used my FB acc.

Gabriel also got the same error

![image](https://user-images.githubusercontent.com/26440947/35592648-870fb778-05c2-11e8-8d17-712006552472.png)

![image](https://user-images.githubusercontent.com/26440947/35592652-8aa9aa92-05c2-11e8-9817-709ffd152bc1.png)

**Comment by jcii** [comment]
I'm perplexed by this one; I tried from my wife's phone and it works. The Facebook 'app' is configured to use the production site.  Can you open a private/incognito web session and see if it happens or if it works? This might take some troubleshooting.

**Comment by jcii** [comment]
ok, found it; not sure why my wife was marked as a 'developer', maybe because we're on the same IP? Anwyay, I have to do this...does Casa have a privacy policy?

![image](https://user-images.githubusercontent.com/593930/35601274-00839c04-05e7-11e8-9436-f2e5e5084384.png)

**Comment by jcii** [comment]
Fixed. had 4 successful tests from random people. Used casa's privacy policy statement.

**Comment by esteban-gs** [comment]
FB Auth. failed on Firefox and Chrome: 

Chrome:
![image](https://user-images.githubusercontent.com/26440947/35652009-bf971d26-06d9-11e8-8564-16b2134954af.png)
version:
![image](https://user-images.githubusercontent.com/26440947/35652021-ce756334-06d9-11e8-92ed-8a5a98954ef7.png)

FireFox:
![image](https://user-images.githubusercontent.com/26440947/35652031-d67ada32-06d9-11e8-897d-9229edfc1cc0.png)
version: 
![image](https://user-images.githubusercontent.com/26440947/35652051-ede4f234-06d9-11e8-8dc0-88c4d9431f9c.png)

Shirley also tried to sign in with FB Auth. It worked initially, but she got stuck on the finalize page.
![jfjfgjg](https://user-images.githubusercontent.com/26440947/35653346-a7ce9db4-069c-11e8-8535-1e8817cb816c.png)
