### ISSUE TITLE
Mystery hirer UI field 

### ISSUE THREAD

**Issue by esteban-gs** [SavageLearning/Machete#288]
"Additional notes to dispatcher" field exists in the UI, but is nowhere to be found in Manager Machete. refer to WO 90313. This field is redundant and may need to be hidden/removed.

**Comment by jcii** [comment]
The additionalNotes is a field in the database, but you're correct it was removed from the Machete page a while ago. I'll remove it from the new one as well.

**Comment by esteban-gs** [comment]
Tested and FB Auth. still failed on Firefox and Chrome:

Chrome:
![image](https://user-images.githubusercontent.com/26440947/35652902-8de1e5b6-069a-11e8-8c7e-1fe5076a983a.png)

version:
![image](https://user-images.githubusercontent.com/26440947/35652909-94f836c0-069a-11e8-9f48-29ce95a06c13.png)


FireFox:
![image](https://user-images.githubusercontent.com/26440947/35652916-9f63219c-069a-11e8-8add-70a9f95f91d1.png)

version:
![image](https://user-images.githubusercontent.com/26440947/35652925-a7974ec4-069a-11e8-9d19-295027ac89ae.png)

**Comment by esteban-gs** [comment]
Looks good. It is no longer in the form.
