### ISSUE TITLE
DateTimeofWork: time selector fails in hirer UI.

### ISSUE THREAD

**Issue by esteban-gs** [SavageLearning/Machete#289]
minute selector for "time needed" absolutely fails and crashes page when increasing the minutes.

**Comment by jcii** [comment]
What browser? I tested it in current chrome and firefox and it's fine...

**Comment by jcii** [comment]
Works for me on:
Firefox 54.0.1 (64-bit) on Win10
Version 63.0.3239.132 (Official Build) (64-bit) on win10


Fails on :
  IE 11.2007 

Angular says it supports browsers going back to like iE9, so we'll have to dig into this one a bit:
https://angular.io/guide/browser-support

**Comment by esteban-gs** [comment]
It failed for me on:
Chrome Version 64.0.3282.119 (Official Build) (64-bit)
Firefox Version 58.0.1 (64-bit)

**Comment by jcii** [comment]
Britchie
The date/time picker is a little awkward.

I thought it was just a date picker at first. I didn't realize it was asking me to enter a time until it threw a validation error.

**Comment by esteban-gs** [comment]
tested and issue is still there.

**Comment by esteban-gs** [comment]
Issue tested and it appears to be fixed
