### ISSUE TITLE
Hirer UI: allows times too close to the order creation date. It needs to have at least a 48 hours (2 business days) delay.

### ISSUE THREAD

**Issue by esteban-gs** [SavageLearning/Machete#290]

**Comment by jcii** [comment]
So this was set to 48 hours, but the datetime math is executed from now, like:
```
if requestedTime < datetime.now() + 48 
  print "too soon"
```

do you want at least 48 hours in the future of the start of the next business day?

**Comment by esteban-gs** [comment]
Yes, at least 48 hours before the start of the next business day.

Business days:
Monday
Tues
Wed
Thur
Fri
Sat

**Comment by jcii** [comment]
So...if they order on Monday, it has to be at least Thursday?

**Comment by esteban-gs** [comment]
Is this issue fix live?

**Comment by jcii** [comment]
yea
