### ISSUE TITLE
Hirer UI: Add text description boxes on some finalize fields

### ISSUE THREAD

**Issue by esteban-gs** [SavageLearning/Machete#294]
On hirer UI, at finalize page, "Transport Method" and  "labor costs" need a description box 

Something like:
"Labor Costs: $110  
To be paid directly to workers in cash at end of work-day"

""Transport Fees: $15
 Due now and payable through this form via a secure PayPal form".

**Comment by esteban-gs** [comment]
missing this part: 
"Transport Fees: $15
Due now and payable through this form via a secure PayPal form".

**Comment by jcii** [comment]
It's there, but it's inside the paypal <div>, so it appears after the finalize. 
![image](https://user-images.githubusercontent.com/593930/36355665-9300974a-149b-11e8-8189-8c6f38933b63.png)

Do you want text there before the finalize?

**Comment by esteban-gs** [comment]
Both before and after.
