### ISSUE TITLE
Pomona needs employer recovered

### ISSUE THREAD

**Issue by jcii** [SavageLearning/Machete#330]
EmployerID 2002

This looks like a good description of how to do the copy programmatically. 
https://intelequia.com/blog/post/735/query-and-transfer-data-between-azure-sql-databases

**Comment by chaim-sw** [comment]
this has been done

<img width="1385" alt="screen shot 2018-07-01 at 12 36 56 pm" src="https://user-images.githubusercontent.com/24903186/42138043-c6bcb5a2-7d2b-11e8-8f12-01ffd45d4e42.png">
