### ISSUE TITLE
PASADENA NEEDS THINGS FIXED

### ISSUE THREAD

**Issue by gaggiae** [SavageLearning/Machete#354]
1. When they are dispatching, on the computer they can add all the data, but when they go to print, the names of the workers don't show up, not does the sum of the cost if there is more than one worker.
2. En la seccion de Skills : need to change/add
3. Salario:  HHH 3 hours- can they choose the salary? Right now the salaries they can choose from are set from Casa Latina I think. 
4. “Time needed”- add additional time starting at 6 am
5. When making ID’s - ID looks good on the computer but then when they print it, an extra number appears. Is that actually the ID software?

**Comment by esteban-gs** [comment]
Emily, let me look at this tonight. Some of these can be done by Pasadena's Machete main user (admin).

**Comment by esteban-gs** [comment]
On #1, It looks like Workers are not even being assigned to the work orders. Also, Work orders are being marked as completed with no workers assigned.
![image](https://user-images.githubusercontent.com/26440947/44554101-83df3d80-a6e4-11e8-8f42-efce42f4372c.png)


![image](https://user-images.githubusercontent.com/26440947/44554122-99546780-a6e4-11e8-8667-7eddc311ba31.png)

**Comment by gaggiae** [comment]
hmm, that is strange. So, I should tell him that in order to have the names and totals for the workers to show up on the work order, they need to enter the names of the workers? (!)

**Comment by gaggiae** [comment]
hello! Quick question about Pasadena. Luis nor his main volunteer have administrative access. they want to create new activities that are not listed and they want to change the salaries offered with HHH. Should I grant them administrative access or is there a reason not to?

**Comment by gaggiae** [comment]
Last request per my conversation with luis:
Can we please make it possible for who ever is dispatching the work to be able type in how much they want to charge for the HHH salary? Right now we have a predetermined price for the HHH work and they want to be able to choose how much to charge.

**Comment by esteban-gs** [comment]
**Q4-When making ID’s - ID looks good on the computer but then when they print it, an extra number appears. Is that actually the ID software?**

Machete doesn't create the IDs, but Machete does issue the Membership Number. Worker records have to be created on Machete first. Machete will create a unique Member number. 

A staff member has to actually put this number into the ID software manually. The ID software converts it to a barcode. Machete won't allow more/less than 5 numbers for sign in purposes.  

So, if the printer is passing six number values through the barcode, this might be an issue. See image below.

![image](https://user-images.githubusercontent.com/26440947/44561718-e814f800-a70a-11e8-80c9-c3526179cea8.png)

**Comment by esteban-gs** [comment]
**Q5 - “Time needed”- add additional time starting at 6 am**
I'll make this a separate issue.

**Comment by chaim1221** [comment]
Thanks for triaging this, Esteban
