### ISSUE TITLE
Please make test site for NICE NY

### ISSUE THREAD

**Issue by gaggiae** [SavageLearning/Machete#356]
Can someone make a test site for NICE so the new staff can explore the functions/features? Thanks!

**Comment by chaim1221** [comment]
Nice has a site. I will update it.

**Comment by chaim1221** [comment]
We don't do "test" sites for individual centers. They can play around on their live site.

**Comment by gaggiae** [comment]
ok thanks

**Comment by chaim1221** [comment]
This has been done and Anthony has an admin account.
