### ISSUE TITLE
can't change base rate for general labor

### ISSUE THREAD

**Issue by chaim1221** [SavageLearning/Machete#383]
steps to reproduce

create an employer
create a work order
view work assignment; general labor; e.g., $12/hr. (do not save assignment)

go to lookups configuration, change rate of general labor to $18/hr.
(all other fields save and update just fine)
save the lookup

go to employer
go to work order(new or old, doesn't matter)
note base rate for general labor is still $12/hr.

doesn't change

**Comment by jcii** [comment]
This is probably the LookupCache; it changes, but you need to wait for the cache to expire. If you look at the Lookups table using SSMS (dont use Machete), I bet you'll see it change.
