### ISSUE TITLE
Events fail to save on update

### ISSUE THREAD

**Issue by chaim1221** [SavageLearning/Machete#387]
This was discovered in Voz's onsite 2018 training:

Okay so worker event attachments are not working for voz, chaim, or test; voz and chaim are on 1.12; they _do_ work for Mountain View (tried it in desperation), also on 1.12. I can troubleshoot these later on today but it does kind of affect our training.

![image](https://user-images.githubusercontent.com/3819970/45010888-8b47f600-afc4-11e8-8077-625a823d4b59.png)

**Comment by jcii** [comment]
This is fixed on the 1.12.x release branch, and the 1.13.x branch. need to deploy to centres.
