### ISSUE TITLE
Online orders still creating orders in the past

### ISSUE THREAD

**Issue by jcii** [SavageLearning/Machete#400]
The validator initially works (not letting orders happen in the past), but somehow it's getting disabled and then the user is changing it.

**Comment by chaim1221** [comment]
Unable to reproduce:
<img width="758" alt="Screen Shot 2020-01-23 at 4 51 12 AM" src="https://user-images.githubusercontent.com/3819970/72978502-3153f600-3d9c-11ea-845c-4fd8a7584b9e.png">

If you change a date to the past it sets it to the first available date.
