### ISSUE TITLE
Machete V1 - Activities not saving edits

### ISSUE THREAD

**Issue by esteban-gs** [SavageLearning/Machete#407]
Activities are not editable once created

**Comment by esteban-gs** [comment]
Getting work from prod staff that they this issue is affecting prod. Please triage.

**Comment by chaim1221** [comment]
I can confirm. Activities can be neither edited nor deleted. I do not know what's causing this. I tried to look at my code locally but discovered #423 so I will need to fix that before I can start working on this one.

Issue level: High, no suggested workaround

**Comment by jcii** [comment]
been deployed for a couple of days...no issues reported. closing.
