### ISSUE TITLE
chaim1221/Machete: Requested unknown parameter *ID from the data source for row 0

### ISSUE THREAD

**Issue by chaim1221** [SavageLearning/Machete#415]
![screen shot 2019-01-15 at 12 59 17 pm](https://user-images.githubusercontent.com/3819970/51209633-8cb7f200-18c5-11e9-9c18-577676a8ec50.png)

This is all over the app and would prevent the Selenium tests from working. Something about the responses from the server are different than what jQuery|DataTables are expecting. Diagnose and fix.

**Comment by jcii** [comment]
Id look at the raw json returned from the ajac handler. Theres probably a 'data' node added or something lime that

**Comment by chaim1221** [comment]
Alright this is up next.

**Comment by chaim1221** [comment]
so the error is descriptive, somehow in the json it's coming across as { woid, waid, eid } etc. instead of the capitalized versions. I have searched my changes to see if I did anything to cause this, and I didn't find anything, so I'm going ahead with just making them all lowercase.

**Comment by chaim1221** [comment]
this has been resolved in chaim1221#2 -- basically, the Core controllers are giving different field names back for the JSON, so had to update the mUI side JavaScript/DataTables code to account for that
