### ISSUE TITLE
Online Hiring: Authenticated emails not saving to employer email field

### ISSUE THREAD

**Issue by esteban-gs** [SavageLearning/Machete#422]
```
select * from employers 
where ID = 51332
```

![image](https://user-images.githubusercontent.com/26440947/52006048-0df3b500-2480-11e9-8768-add531d7927b.png)

**Comment by jcii** [comment]
```select top 100 e.ID, e.email, w.contactName, w.workSiteAddress1, w.phone, w.dateTimeofWork, w.datecreated, e.onlineSigninID, u.email

from dbo.Employers e
join dbo.WorkOrders w on e.ID = w.EmployerID
join dbo.AspNetUsers u on e.onlineSigninID = u.Id

where w.onlineSource = 1
  and e.email is null
  and w.datecreated > '2019-01-01'

order by w.datecreated desc```

I can populate the Employer.email field; filling in the missing emails is also an update query.
HOWEVER...the email field in the employer is disconnected from the aspnetuser table
editing that wont change the onlineSigninID field in employer, which is the guid from aspnetusers

**Comment by esteban-gs** [comment]
Is the disconnect between the aspnetuser table  and the employer email field permanent?

**Comment by jcii** [comment]
no. they're connected by the onlineSigninID

**Comment by jcii** [comment]
Ok, looking into the code, I made a valiant effort to force the email into that record. Looking at the data, these all look to be newly created records.

**Comment by chaim1221** [comment]
![Screen Shot 2019-03-29 at 1 59 32 PM](https://user-images.githubusercontent.com/3819970/55262421-ef652c80-522a-11e9-9422-114cdb77df12.png)

**Comment by esteban-gs** [comment]
This took me forever to figure out what was going on. The `employer.email = UserEmail` was called before auto mapper. AutoMapper was overriding the email with `null`

https://github.com/SavageLearning/Machete/blob/7c2f3ed2d71658cc178c3650849a2b7585188c8f/Machete.Web/Controllers/Api/EmployersController.cs#L174

**Comment by chaim1221** [comment]
Can you maybe attach a screenshot of where you're seeing the null value?

**Comment by esteban-gs** [comment]
**Before AutoMapper**
![Screenshot from 2020-02-27 22-04-34](https://user-images.githubusercontent.com/26440947/75514911-80013b00-59ad-11ea-9d74-51172ba46bad.png)
**After AutoMapper**
![Screenshot from 2020-02-27 22-05-07](https://user-images.githubusercontent.com/26440947/75514920-82639500-59ad-11ea-8770-f6d2e67bb4e6.png)

**Comment by chaim1221** [comment]
woot! thanks

**Comment by esteban-gs** [comment]
I believe the Created online is not being set either. Will check
