### ISSUE TITLE
chaim1221/Machete -- password checker fails silently and does not create user

### ISSUE THREAD

**Issue by chaim1221** [SavageLearning/Machete#446]
![image](https://user-images.githubusercontent.com/3819970/58126611-2cfd8a80-7bc8-11e9-8f87-513ed5ba3a7d.png)

may be rel. #435

**Comment by esteban-gs** [comment]
Unable to recreate after adding stricter psswd requirements. 

Tested on `Manage` and `Account/Edit`
![image](https://user-images.githubusercontent.com/26440947/75134114-28ec2500-5692-11ea-9424-2f8550450852.png)
