### ISSUE TITLE
chaim1221 some views take long time to load

### ISSUE THREAD

**Issue by chaim1221** [SavageLearning/Machete#449]
simple views, doesn't make sense

e.g., worker create

```
info: Microsoft.AspNetCore.Mvc.ViewFeatures.PartialViewResultExecutor[4]
      Executed PartialViewResult - view Create executed in 20450.4818ms.
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action Machete.Web.Controllers.WorkerController.Create (Machete.Web) in 21179.7535ms
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 21193.6534ms 200 text/html; charset=utf-8
```

**Comment by chaim1221** [comment]
I think this is development only. The site in Test seems snappy enough. Moving to Review for now.

**Comment by motaylorvooz** [comment]
-The Dispatch page view and Worker Sign in view both seem a little sluggish.

**Comment by chaim1221** [comment]
![image](https://user-images.githubusercontent.com/3819970/59165287-5ece8680-8ace-11e9-8eb7-9f965680e2be.png)
test-voz.machetessl.org; 1.14.49; 49000ms, all tabs

![image](https://user-images.githubusercontent.com/3819970/59165323-b66cf200-8ace-11e9-8741-8451acec0422.png)
voz.machetessl.org; 1.13.x; 52000ms, all tabs

**Comment by chaim1221** [comment]
I don't see an issue here. Some pages are more sluggish than their 1.13 counterparts but overall it is the same.

**Comment by chaim1221** [comment]
the long pause in the second picture is a human delay before loading v2. not programmatic.
