### ISSUE TITLE
Expiration date not triggering inactive member value

### ISSUE THREAD

**Issue by esteban-gs** [SavageLearning/Machete#452]
On Machete Legacy, past expiration date is no longer triggering the Member status field to be set to "Expired".

Example below shows the expiration date is past the current date.
![image](https://user-images.githubusercontent.com/26440947/58516291-4ff5e480-815c-11e9-9a9c-f70e7686d7a8.png)

**Comment by chaim1221** [comment]
A big note about this one: This was reported in 1.13 and is not necessary for dotnet core completion.

**Comment by esteban-gs** [comment]
Will close after through testing.

**Comment by chaim1221** [comment]
This has been deployed.
