### ISSUE TITLE
chaim1221/Machete: forms have semicolons everywhere

### ISSUE THREAD

**Issue by chaim1221** [SavageLearning/Machete#463]
this is from the conversion from asp.net MVC razor to Razor Pages (fused with MVC in Core).

find them all and destroy. Should be a simple search/replace once the pattern is found.

**Comment by esteban-gs** [comment]
![image](https://user-images.githubusercontent.com/26440947/61158935-437cdf80-a4af-11e9-9501-65fa9d716995.png)

**Comment by chaim1221** [comment]
https://user-images.githubusercontent.com/26440947/61158837-01ec3480-a4af-11e9-9e82-0ead0ff82d52.png
