### ISSUE TITLE
can't delete work assignment from list

### ISSUE THREAD

**Issue by motaylorvoz** [SavageLearning/Machete#465]
![image](https://user-images.githubusercontent.com/51543773/59165517-e79af180-8ad1-11e9-8d65-bd6a21e1b986.png)

steps to repro:
1. Go to Employers
2. choose Barbara
3. click on work order
4. click on list work assignments
5. click on a work assignment
6. Delete and save
7. will not save to the work order

**Comment by chaim1221** [comment]
This is important because a worker might get sent to an assignment that doesn't exist. ~Mo
