### ISSUE TITLE
Can't type in another race when creating worker profiles

### ISSUE THREAD

**Issue by motaylorvoz** [SavageLearning/Machete#467]
When you are creating a worker, you are unable to write in a race that is other than any listed in the drop box menu. 

Steps to repro:
1. Go to people tab
2. Click create new person and enter in data
3. go to create a new worker
4. try to type in another race........no can do

**Comment by chaim1221** [comment]
This is by design. The race data is for reporting and fundraising purposes. The set is defined by the lookups. If you want a new race, add a lookup.
