### ISSUE TITLE
1.14.78 saves client time as UTC for WorkOrder Edit

### ISSUE THREAD

**Issue by chaim1221** [SavageLearning/Machete#488]
For some reason when I edit or complete a work order, it changes the time to 7 hours earlier?
These definitely were not meant for 2am and 4am

![image](https://user-images.githubusercontent.com/3819970/60118050-501fda80-9730-11e9-95b9-c11bdfff8667.png)

 Should be 9am and 11am, respectively. Everything seems fine when I create a new work order. Just changes the time when I do any edits.

r/b Annica

**Comment by chaim1221** [comment]
chaim1221#29

**Comment by chaim1221** [comment]
jcii/machete-kvm#27

**Comment by esteban-gs** [comment]
Already fixed, closing.
