### ISSUE TITLE
Legacy/Dispatch view, not changing row color on canceled orders

### ISSUE THREAD

**Issue by esteban-gs** [SavageLearning/Machete#491]

**Comment by chaim1221** [comment]
Unable to reproduce.

![Screen Shot 2019-07-03 at 12 44 41 PM](https://user-images.githubusercontent.com/3819970/60621221-f489c880-9d91-11e9-93c1-52662c209cf2.png)
![Screen Shot 2019-07-03 at 12 53 55 PM](https://user-images.githubusercontent.com/3819970/60621222-f489c880-9d91-11e9-8593-24f01c39e216.png)

**Comment by esteban-gs** [comment]
Try the **Dispatch** view:
What should happen 
![image](https://user-images.githubusercontent.com/26440947/61166073-2eb74080-a4dd-11e9-9cbe-a6ee01f2934d.png)

What **actually** happens 
![image](https://user-images.githubusercontent.com/26440947/61166114-6faf5500-a4dd-11e9-931f-2c1e4125381d.png)

**Comment by chaim1221** [comment]
I don't know why it's not doing it for the Casa site. This for the second time is the dispatch view on Voz (see screenshots above). I will try to troubleshoot for Casa.

![image](https://user-images.githubusercontent.com/3819970/61178299-540c8300-a59f-11e9-8d63-b0bd42dab9e2.png)

**Comment by chaim1221** [comment]
![image](https://user-images.githubusercontent.com/3819970/61178424-a77fd080-a5a1-11e9-86bf-d8aacaee0a5c.png)

Casa Latina, dispatch view

**Comment by esteban-gs** [comment]
Nice. It is working now.

**Comment by esteban-gs** [comment]
No longer present as of version 1.14.235, closing.
