### ISSUE TITLE
Fix Datetime in WorkOrder summary.

### ISSUE THREAD

**Issue by esteban-gs** [SavageLearning/Machete#507]
Workorder summary datetime column doesn't match weekday column:

![image](https://user-images.githubusercontent.com/26440947/61166320-3a583680-a4e0-11e9-9baf-e4449a454625.png)

**Comment by esteban-gs** [comment]
also this screenshot gif might help: https://savagelearning.slack.com/archives/C0DJEU0E9/p1562986473022200

**Comment by chaim1221** [comment]
Duplicate of #505
