### ISSUE TITLE
kvm: need to manage space on backup volume

### ISSUE THREAD

**Issue by jcii** [SavageLearning/Machete#511]
Currently at 65% ... 

look to see if Duplicati has a management method, since it's doing fancy block-level things.

**Comment by jcii** [comment]
https://forum.duplicati.com/t/new-retention-policy-deletes-old-backups-in-a-smart-way/2195

**Comment by chaim1221** [comment]
1. extend the qcow2 files by 10GB each so we have some more room

then do #534

**Comment by chaim1221** [comment]
This was done as part of the backups story, see PRs 34 and 36-42 in the KVM repo.
