### ISSUE TITLE
Edit my-work-orders navigates to `undefined`

### ISSUE THREAD

**Issue by chaim1221** [SavageLearning/Machete#516]
In V2, start at my-work-orders with ~just one~ any number of orders:

![image](https://user-images.githubusercontent.com/3819970/61586213-72382d00-ab23-11e9-9218-dbefcdcfcbfe.png)

Click edit:

![image](https://user-images.githubusercontent.com/3819970/61586209-5c2a6c80-ab23-11e9-9d4a-3f556c5af150.png)

Sadness

**Comment by esteban-gs** [comment]
No longer present. Closing.
