### ISSUE TITLE
5pm Work Assignments show in next day (UTC comparison)

### ISSUE THREAD

**Issue by chaim1221** [SavageLearning/Machete#519]
1.14.117

![Screen Shot 2019-07-23 at 12 16 55 AM](https://user-images.githubusercontent.com/3819970/61691138-c25bee80-acdf-11e9-8825-818473167f6b.png)

**Comment by chaim1221** [comment]
These were for 7/22 at 5pm. Because of the time differential (+7h), UTC comparison thinks they are for 7/23. Examples of how to fix this are in `master` at WorkerSigninService and I _think_ WorkOrderService but check. Comparison of dates should always be client dates for values that affect clients.

**Comment by chaim1221** [comment]
https://github.com/SavageLearning/Machete/issues/564#issue-513065258

**Comment by esteban-gs** [comment]
No longer present as of version 1.14.235, closing.
