### ISSUE TITLE
1.14.139 WorkOrder/Index performance is poor; query is duplicated; load times >9s

### ISSUE THREAD

**Issue by chaim1221** [SavageLearning/Machete#528]
Casa Latina reports slow Work Orders page. This screenshot was provided:

![image](https://user-images.githubusercontent.com/3819970/62069928-446f7a00-b1ee-11e9-9f31-0ed0c0c7b4e1.png)

The double query is not new and seems to run concurrently (may be by design, but it's a smell); nevertheless, load time should not be this slow. May be related to other Ajax issues.

**Comment by chaim1221** [comment]
Jimmy: On the Summary page, you doubleclick, and it brings up that page in handler for the day you clicked on. it's doing the query twice.

![image](https://user-images.githubusercontent.com/3819970/62070509-79300100-b1ef-11e9-9f74-d651e4356371.png)

**Comment by jcii** [comment]
https://github.com/chaim1221/Machete/pull/49

**Comment by jcii** [comment]
pretty sure this is done. looking at casa prod now and workorder/index is fast.
