### ISSUE TITLE
1.14.139 Search by string okay, but search by date takes > 5s

### ISSUE THREAD

**Issue by chaim1221** [SavageLearning/Machete#529]
![image](https://user-images.githubusercontent.com/3819970/62071073-96b19a80-b1f0-11e9-8b69-f0100414fb68.png)

This may have to do with the DbFunctions replacements at the search index layer. The date comparisons should be improved.

**Comment by jcii** [comment]
Fixed in https://github.com/chaim1221/Machete/pull/49
