### ISSUE TITLE
Better DBA backup scripting

### ISSUE THREAD

**Issue by jcii** [SavageLearning/Machete#534]
Ola's backup https://ola.hallengren.com/sql-server-backup.html will backup all user databases on a server in a handy tree structure. It will also encrypt using our cert or key.

We should use Ola's script to do FULL backups, and release the current method of downing the SQL Server container.

With Store Procedures installed, this should work:
```
USE master;
GO
CREATE MASTER KEY ENCRYPTION BY PASSWORD = 'secret!';
GO
CREATE CERTIFICATE MyTestDBBackupEncryptCert
   WITH SUBJECT = 'MyTestDB Backup Encryption Certificate';
GO

EXECUTE dbo.DatabaseBackup
@Databases = 'USER_DATABASES',
@BackupType = 'FULL',
@Verify = 'Y',
@Compress = 'Y',
@CheckSum = 'Y',
@Directory = '/var/opt/mssql/backup',
@Credential = 'machetebackupcredential1',
@Encrypt = 'Y',
@EncryptionAlgorithm = 'AES_256',
@ServerCertificate = 'MyTestDBBackupEncryptCert';
```

We need to figure out how to export the CERTIFICATE; we'll need it for restore. There's a warning on the SQL console about it when you try to use it.

Round 2:
SQL Server can backup directly to Azure. However, this is busted on linux:
```2019-08-04 03:28:41.68 Backup      BACKUP failed to complete the command BACKUP DATABASE blueprint_db. Check the backup application log for detailed messages.
^MVDI: "C:\binn\BackupToUrl.exe"
```
https://github.com/MicrosoftDocs/sql-docs/issues/2150

If they get that fixed, then we should see if we want Ola's script to go straight to Azure:

https://docs.microsoft.com/en-us/sql/relational-databases/tutorial-sql-server-backup-and-restore-to-azure-blob-storage-service?view=sql-server-2017

**Comment by chaim1221** [comment]
This has been done, see KVM PRs 34, 36-42.
