### ISSUE TITLE
Sanctioned/Expelled Warning Not Showing on Signin

### ISSUE THREAD

**Issue by chaim1221** [SavageLearning/Machete#545]
I thought there was an issue for this but I can't find it. Latest Machete versions up to 1.14.158 are not displaying the sanctioned/expelled warning on the Worker Signin tab. It works for Activities, so my suggestion would be to check the Activities code against the Worker Signin code; this is all UI.

Could have to do with ID casing (ID vs id). Could have to do with the callback function in DataTables. Check both.

**Comment by jcii** [comment]
![image](https://user-images.githubusercontent.com/593930/72761887-52e19180-3b92-11ea-9dfa-b2d5070ff40d.png)

The `member*` properties aren't getting set on the data object returned. 

The code is looking for 
```
                        if (data.memberSanctioned || data.memberExpelled) {
                            $("#wsiRedImage").attr('src', data.imageRef);
                            $('#signin-red-dialog').dialog({ 
```
to display the dialog

**Comment by jcii** [comment]
These are populated by AutoMapper when the Domain object is mapped to a ViewModel object.
```
            CreateMap<Domain.WorkerSignin, ViewModel.WorkerSignin>()
                .ForMember(v => v.memberExpired, opt => opt.MapFrom(d => d.worker.memberStatusID == Domain.Worker.iExpired))
                .ForMember(v => v.memberInactive, opt => opt.MapFrom(d => d.worker.memberStatusID == Domain.Worker.iInactive))
                .ForMember(v => v.memberSanctioned, opt => opt.MapFrom(d => d.worker.memberStatusID == Domain.Worker.iSanctioned))
                .ForMember(v => v.memberExpelled, opt => opt.MapFrom(d => d.worker.memberStatusID == Domain.Worker.iExpelled))
```

I suspect my janky-static-class properties, where I store the lookup integers that go with memberStatus, are not populated.

**Comment by jcii** [comment]
yea...also fixed this is Swagger branch... need to populate static ids on initialization

**Comment by esteban-gs** [comment]
The conditional colors are showing: 
![image](https://user-images.githubusercontent.com/26440947/77242184-e9452a00-6bb8-11ea-8831-9fd3d770fc37.png)

**Comment by chaim1221** [comment]
is this done?

**Comment by esteban-gs** [comment]
Yes.
