### ISSUE TITLE
Cannot see Activities for workers who are inactive

### ISSUE THREAD

**Issue by chaim1221** [SavageLearning/Machete#549]
Reproduce:

1. Make a worker.
2. Worker inactive.
3. Make an activity.
4. Sign worker into activity.
5. Go to worker profile.

Cannot see activities.

**Comment by esteban-gs** [comment]
I was not able to reproduce. Worker activities show sign in.

**Comment by esteban-gs** [comment]
Closing, cannot reproduce on version 1.14.186
