### ISSUE TITLE
Client reports time issue with activities

### ISSUE THREAD

**Issue by chaim1221** [SavageLearning/Machete#562]
Start and end date are being set to the same thing. Happening at Casa Latina in prod. v1.14.156. Screenshot not available. Slack:

https://savagelearning.slack.com/archives/C9HR5HS3B/p1570569218026200

Diagnose and resolve. Medium priority.

**Comment by esteban-gs** [comment]
Activities start datetime changes to the end datetime value after saving:

![image](https://user-images.githubusercontent.com/26440947/66434590-b8d94d00-e9d7-11e9-8c84-e73b13906cd0.png)

**Comment by esteban-gs** [comment]
https://github.com/chaim1221/Machete/blob/bff6215b5bfb985a3961bf883fff93d76f865fa4/Machete.Web/Maps/Legacy/ActivityProfile.cs#L19

` .ForMember(v => v.dateStart, opt => opt.MapFrom(d => d.dateEnd.UtcToClient()))`

Should be:
` .ForMember(v => v.dateStart, opt => opt.MapFrom(d => d.dateStart.UtcToClient()))`
