### ISSUE TITLE
version 1.14.183 configure lookups broken

### ISSUE THREAD

**Issue by chaim1221** [SavageLearning/Machete#569]
See #414 and #410 to see if they contain useful information

redirects to V2; that could be a permissions issue

check the logs while attached to a ~prod~ `test` environment database.

**Comment by esteban-gs** [comment]
Getting this while attached to test environment db:
`InvalidOperationException: The view '~/Views/Config/Index.cshtml' was not found. The following locations were searched:
~/Views/Config/Index.cshtml
Microsoft.AspNetCore.Mvc.ViewEngines.ViewEngineResult.EnsureSuccessful(IEnumerable<string> originalLocations)`

Was able to fix locally  by replacing `Config` with `Lookups` here: 

https://github.com/SavageLearning/Machete/blob/c1e0c82a58175b33c82565d771d9c013e6aa9a63/Machete.Web/Controllers/Legacy/ConfigController.cs#L93
