### ISSUE TITLE
Activities won't delete

### ISSUE THREAD

**Issue by esteban-gs** [SavageLearning/Machete#579]
on version 1.14.186.

Activities won't delete. 

...Also, it is not letting me delete activities that are repeats. I have 2 that were entered twice.

**Comment by jcii** [comment]
So, connecting to dr-test/casa_db via tunnel, running the latest code from /develop

I was just able to delete an Activity with no sign-ins. I noticed that the List display didn't update.

Trying to delete an activity with sign-ins now... that looks to also work. 

can you tell me a record on test-casa that you aren't able to delete?

**Comment by esteban-gs** [comment]
On dr-test, the activity for 1/20 under my user name
