### ISSUE TITLE
Create Users fails with 2+ words in last/first name fields

### ISSUE THREAD

**Issue by esteban-gs** [SavageLearning/Machete#580]
version 1.14.186
###Create Users fails with 2+ words in last/first name fields
``warn: Microsoft.AspNetCore.Identity.UserManager[13]
      User {some guid} validation failed: InvalidUserName.``

**Comment by jcii** [comment]
Background on the username -- So this was 2011 me thinking forcing people to use their real first and last name was a good idea.

With Single signon and federated auth... (google/facebook/yahoo/twitter logins), email is the default username/userid/whatever. We should adopt that if we're going to change things.

For improving the current situation, some javascript that says 'you can't use spaces, trying JimmySandersCarter (taking the spaces out of my name) is fine.

**Comment by esteban-gs** [comment]
Mitigating the validation feedback to user for now. Will implement the username = email soon.
