### ISSUE TITLE
 cannot see activities for workers randomly

### ISSUE THREAD

**Issue by chaim1221** [SavageLearning/Machete#581]
In #549 we thought that perhaps the Active/Inactive status of a worker was preventing people from seeing the Activities tab on workers that have been signed into activities. Now it seems the bug has re-presented itself, but has more to do with the user requesting the information than anything about the worker.

Your mission should you choose to accept it is to figure out why, on some worker records, some people can see the Activities tab and some people cannot. This will probably involve messing with the jQuery/mUI bit. Given the age of that code, it may be easier to find a different solution.

*We can mitigate by creating a V2 report that lists the activities for a given worker ID.*

More info:

![image](https://user-images.githubusercontent.com/3819970/72575482-71d5e000-3881-11ea-8eb7-6d10c362d22e.png)

**Comment by jcii** [comment]
```
        @if (Html.IsInRole("Teacher") && Model.Worker != null)
        {
            <li><a href="#actJoinList" id="actJoinTab" class="ListTab">@Activities.actJoinTab</a></li>
            <li><a hidden href="/Worker/Edit/@(Model.ID)" id="workerEditTab">@Machete.Web.Resources.Persons.workerinfo</a></li>
        }
```
So the the user has to be a teacher, and the Model.Worker has to exist. I imagine I did that and it's been lost in time... it's not documented in the wiki

**Comment by jcii** [comment]
I'm going to add the administrator & manager to the list of viewers
