### ISSUE TITLE
Validate unique user email when creating/editing user.

### ISSUE THREAD

**Issue by esteban-gs** [SavageLearning/Machete#583]

**Comment by esteban-gs** [comment]
Still need to refactor for performance
 https://github.com/SavageLearning/Machete/blob/1315432538e2ecd1004462d70f8fc905164b4a1d/Machete.Web/Controllers/Legacy/AccountController.cs#L368

**Comment by esteban-gs** [comment]
@esteban-gs still present on 1.14.219-beta

**Comment by Kodazer** [comment]
Test

**Comment by Kodazer** [comment]
Seems to be working well; I'm not sure how universal the feedback is, but could have merit to have more nuance? I wonder if folks would be able to intuit that the email isn't unique.
