### ISSUE TITLE
Need a user type that can add/edit/delete work assignments but not delete employers

### ISSUE THREAD

**Issue by dwcmacheteadmin** [SavageLearning/Machete#81]
Hi,

Our organization uses volunteers for data entry and we train them to create work orders and work assignments.  We give them Manager access since it appears to be the only user type that can create work assignments.  However, Manager access gives them more rights than we prefer to give them.  Specifically, it's the ability to delete Employers that has caused the most problems.

Possible fixes:
1) Give us the ability to manage access rights for each user type.
2) Create a new user type that can manage work assignments but not delete Employers.
3) Add a toggle at the user profile level to allow work assignment maintenance.

Thanks!

**Comment by jcii** [comment]
Hi,

Sorry for the late response on this. If you could email me (jimmy AT ndlon.org), I need to know which member organization you're with...I'm assuming you haven't setup your own instance?

Thanks

**Comment by chaim1221** [comment]
Has there been any activity on this? Was considering closing.

**Comment by dwcmacheteadmin** [comment]
You may close this.  I am no longer volunteering and I doubt there's anyone
there that can follow up on this request.

**Comment by chaim1221** [comment]
Milestone not showing up and original poster (OP) has indicated the issue can be closed.
