### ISSUE TITLE
Can't filter by membership number on Person tab

### ISSUE THREAD

**Issue by misandov** [SavageLearning/Machete#91]
Do you need more info? I will gladly provide.

**Comment by jcii** [comment]
Hi! Thanks for the question.

So, it looks like one of the contractors who worked on Machete while I was away being a dad removed the workers tab. The page is still there, but they have removed the link for it, which is unfortunate.

If you go to this link, https://mountainview.machetessl.org/Worker, you can search by membership number.

**Comment by misandov** [comment]
Thanks
I would like to be part of the project, at least filing issues. I have been doing data entry on the Mountain View center and I have experience programming, so I'd love to help. Is there some way I could reach you or someone else I could talk to?

Thanks

**Comment by jcii** [comment]
email me. user jimmy at the domain name ndlon.org.

**Comment by jcii** [comment]
testing reply to github mail...

**Comment by jcii** [comment]
This is fixed in the latest code
