### ISSUE TITLE
Question: What is the best way to handle duplicated persons?

### ISSUE THREAD

**Issue by misandov** [SavageLearning/Machete#93]
We have several in the system, having the same name and phone number. Many times there is one that is a worker and the other is not.

**Comment by jcii** [comment]
So a Person record is a specific type of record. A Worker separate record, and a Worker record is a child record of a Person. I.e., all Workers are Persons, but not all Persons are Workers. An Employer is a separate type of record.

So, if we're talking about duplicate Person records, one will need to be deleted. Do you know if both records have been used for sign-in activity?

**Comment by misandov** [comment]
Yes, I am talking about duplicated Persons.

Sometimes both of them have SignIn activity, but it's the minority of the
cases.

I have tried to delete Persons when the corresponding Worker doesn't hve
any assignment, but I get an error. I haven't checked if they have signed
in.
