### ISSUE TITLE
Workers with the same membership number

### ISSUE THREAD

**Issue by misandov** [SavageLearning/Machete#95]
Ana and I were adding new workers to the database and somehow they ended having the same membership number. How to fix this? Can I just impose a new number?

**Comment by jcii** [comment]
yes you can change the membership number. it's not the primary key for the worker.

**Comment by misandov** [comment]
Okay, and how is the next worker number computed? let's say: the last
number is 16020 so I change my repeated name to 16021. When in the future I
create a new worker, what will the id number be?

**Comment by asacarrington** [comment]
Is there any logic behind a membership number, can you not convert to a GUID? is this still an issue? or does a fix still need to be implemented to ensure unique membership IDs are provided?

**Comment by jcii** [comment]
Sorry for the late response; I missed the notification. The membership number can change by center. Many centers have existing IDs that they bring with them to the program. The ID of that row in the DB is internal, the membership ID is whatever the center needs it to be.
